FeatureNames,Status,FeatureNames HumanReadable
abd_dual,Found,abdomen dual
dcg_mn,Found partially ,diagnostic cost group mn
dcg_skw,Found partially ,diagnostic cost group skw
dcg_slp,Found partially ,diagnostic cost group slp
edctn_9_12_qty,Found partially ,area education 9-12 size
female_gndr_cd,Found,female gender cd
hspnc_ppltn_qty,Found,hispanic population quantity
lab_sparse_val_Aldolase,Found,lab sparse value aldolase
lab_sparse_val_ApolipoproteinB,Found,lab sparse value apolipo protein b
lab_sparse_val_BilirubinglucuronidatedBilirubinalbuminbound,Found,lab sparse value bilirubin glucuronidated bilirubin albumin bound
lab_sparse_val_Coagulationsurfaceinduced,Found,lab sparse value coagulation surface induced
lab_sparse_val_GlycinemaxAbIgERASTclass,Found,lab sparse value glycine max ab ige rast class
lab_sparse_val_MilkAbIgERASTclass,Found,lab sparse value milk ab ige rast class
lab_sparse_val_OleaeuropaeapollenAbIgERASTclass,Found,lab sparse value olea europaea pollen ab ige rast class
lab_sparse_val_PenicilliumnotatumAbIgERASTclass,Found,lab sparse value penicillium notatum ab ige rast class
lab_sparse_val_PrunusdulcisAbIgERASTclass,Found,lab sparse value prunus dulcis ab ige rast class
lab_sparse_val_Sexhormonebindingglobulin,Found,lab sparse value sex hormone binding globulin
latd_nbr,Found,latitude
